### PR TITLE
Add a geological model example to notebook

### PR DESCRIPTION
**Pull request by ahinoamp**
Hi Marco,

As promised, I'm making a pull request on an example of the geological model.

Also, if you are interested, here is a link to a binder I made:
https://mybinder.org/v2/gh/ahinoamp/Example3DGeologicModelUsingVTKPlotter/master?filepath=geological_model.ipynb

I'll be using the binder to make a short youtube tutorial on using VTKplotter for visualizing geology :-)

Best,
Noe

### CODE REVIEW

**Comment by marcomusy** [comment]
@ahinoamp 
Works beautifully!!
I've also created an equivalent python script, to run it, update vtkplotter:
`pip install -U git+https://github.com/marcomusy/vtkplotter.git`
then type
`vtkplotter -r geological_model`
image
(note that hoovering the mouse pops the name of the object)

I also created a numpy snapshot of the window: https://vtkplotter.embl.es/examples/geo_scene.npy

you can download the file and recreate the whole scene with:
`vtkplotter geo_scene.npy`

Thanks again for the contribution!

**Comment by ahinoamp** [comment]
oh wow! that's amazing. I like the look of that grid and the interactivity.
I'll take a look soon and then maybe update my code as well.

Thanks again for all your help! Great package.
Noe

**Comment by marcomusy** [comment]
Hi again :) in trying to make the script more didactic for new users I found a couple of simplifications and a couple of additions that you may actually find useful:

- the color scale can be stretched from below with keyword `vmin`
- use of `flag()` to pop the text ..but not available in notebooks :(
- added `isolines()` to better visualize the heights
- form a black wall by extruding the Line
- can change the scale of all object asymmetrically with `mesh.scale()`
- can optionally export to k3d the result with `exportWindow("page.html")` from within the script.
- the last loop in the original notebook was not necessary!

the result is:
```python
"""Recreate a model of a geothermal reservoir, Utah
(Credits: A. Pollack, SCRF)"""
from vtkplotter import Plotter, Mesh, Points, Line, Lines, printc, exportWindow
import pandas as pd
from scipy.spatial import Delaunay


# Load surfaces, import the file from github
printc("...loading data...", invert=1)
url = "https://raw.githubusercontent.com/ahinoamp/Example3DGeologicModelUsingVTKPlotter/master/"

landSurfacePD = pd.read_csv(url+"land_surface_vertices.csv")
vertices_175CPD = pd.read_csv(url+"175C_vertices.csv")
vertices_225CPD = pd.read_csv(url+"225C_vertices.csv")
Negro_Mag_Fault_verticesPD = pd.read_csv(url+"Negro_Mag_Fault_vertices.csv")
Opal_Mound_Fault_verticesPD = pd.read_csv(url+"Opal_Mound_Fault_vertices.csv")
top_granitoid_verticesPD = pd.read_csv(url+"top_granitoid_vertices.csv")
microseismic = pd.read_csv(url+"Microseismic.csv")

# The well path and different logs for the well paths
well_5832_path = pd.read_csv(url+"path5832.csv")
temp_well = pd.read_csv(url+"temperature5832.csv")
nphi_well = pd.read_csv(url+"nphi5832.csv")
pressure_well = pd.read_csv(url+"pressure5832.csv")

# Since most of the wells in the area were just vertical, I split them into two files:
# One file with the top of the wells and the other with the bottom point of the wellbore
wellsmin = pd.read_csv(url+"MinPointsWells.csv")
wellsmax = pd.read_csv(url+"MaxPointsWells.csv")

# Project boundary area on the surface
border = pd.read_csv(url+"FORGE_Border.csv")


#############################################
## 1. land surface: a mesh with varying color
#############################################
printc("...analyzing...", invert=1)

# perform a 2D Delaunay triangulation to get the cells from the point cloud
tri = Delaunay(landSurfacePD.values[:, 0:2])

# create a mesh object for the land surface
landSurface = Mesh([landSurfacePD.values, tri.simplices])

# in order to color it by the elevation, we use the z values of the mesh
zvals = landSurface.points()[:, 2]
landSurface.pointColors(zvals, cmap="terrain", vmin=1000)
landSurface.name = "Land Surface" # give the object a name

# Create a plotter and add landSurface to it
plt = Plotter(axes=dict(xtitle='km', ytitle=' ', ztitle='km*1.5', yzGrid=False),
              size=(1200,900))    # screen size
plt += landSurface.flag()         # this adds a flag when hoovering the mouse
plt += landSurface.isolines(5).lw(1).c('k')

#############################################
## 2. Different meshes with constant colors
#############################################
# Mesh of 175 C isotherm
tri = Delaunay(vertices_175CPD.values[:, 0:2])
vertices_175C = Mesh([vertices_175CPD.values, tri.simplices]).c("orange").opacity(0.3)
vertices_175C.name = "175C temperature isosurface"
plt += vertices_175C.flag()

# Mesh of 225 C isotherm
tri = Delaunay(vertices_225CPD.values[:, 0:2])
vertices_225CT = Mesh([vertices_225CPD.values, tri.simplices]).c("red").opacity(0.4)
vertices_225CT.name = "225C temperature isosurface"
plt += vertices_225CT.flag()

# Negro fault
tri = Delaunay(Negro_Mag_Fault_verticesPD.values[:, 1:3])
Negro_Mag_Fault_vertices = Mesh([Negro_Mag_Fault_verticesPD.values, tri.simplices])
Negro_Mag_Fault_vertices.name = "Negro Fault"
plt += Negro_Mag_Fault_vertices.c("f").opacity(0.6).flag()

# Opal fault
tri = Delaunay(Opal_Mound_Fault_verticesPD.values[:, 1:3])
Opal_Mound_Fault_vertices = Mesh([Opal_Mound_Fault_verticesPD.values, tri.simplices])
Opal_Mound_Fault_vertices.name = "Opal Mound Fault"
plt += Opal_Mound_Fault_vertices.c("g").opacity(0.6).flag()

# Top Granite
xyz = top_granitoid_verticesPD.values
xyz[:, 2] = top_granitoid_verticesPD.values[:, 2] - 20
tri = Delaunay(top_granitoid_verticesPD.values[:, 0:2])
top_granitoid_vertices = Mesh([xyz, tri.simplices]).c("darkcyan")
top_granitoid_vertices.name = "Top of granite surface"
plt += top_granitoid_vertices.flag()

####################
## 3. Point objects
####################
printc("...plotting...", invert=1)

# FORGE Boundary. Since the boundary area did not have a Z column,
# I assigned a Z value for where I wanted it to appear
border["zcoord"] = 1650
borderxyz = border[["xcoord", "ycoord", "zcoord"]]
boundary = Line(borderxyz.values).extrude(zshift=120, cap=False).c("k")
boundary.name = "FORGE area boundary"
plt += boundary.flag()

# Microseismic
microseismicxyz = microseismic[["xloc", "yloc", "zloc"]]
scals = microseismic[["mw"]]
microseismicPts = Points(microseismicxyz.values, r=4).pointColors(scals, cmap="jet")
microseismicPts.name = "Microseismic events"
plt += microseismicPts.flag()

####################
## 4. Line objects
####################
# The path of well 58_32
xyz = well_5832_path[["X", "Y", "Z"]].values
Well = Line(xyz)
Well.name = "Well 58-32"
plt += Well.flag()

# A porosity log in the well
xyz = nphi_well[["X", "Y", "Z"]].values
porosity = nphi_well["Nphi"].values
Well = Line(xyz).pointColors(porosity, cmap="hot").c("gold").lw(2)
Well.name = "Porosity log well 58-32"
plt += Well.flag()

# This well data is actually represented by points since as of right now,
xyz = pressure_well[["X", "Y", "Z"]].values
pressure = pressure_well["Pressure"].values
Well = Points(xyz, r=1).pointColors(pressure, cmap="cool")
Well.name = "Pressure log well 58-32"
plt += Well.flag()

# Temperatue log
xyz = temp_well[["X", "Y", "Z"]].values
temp = temp_well["Temperature"].values
Well = Points(xyz, r=1).pointColors(temp, cmap="seismic")
Well.name = "Temperature log well 58-32"
plt += Well.flag()

#########################
## 5. Multi-line objects
#########################
# defining the start and end of the lines that will be representing the wellbores
Wells = Lines(wellsmin[["x", "y", "z"]].values, # start points
              wellsmax[["x", "y", "z"]].values, # end points
              c="gray", alpha=1, lw=3)
Wells.name = "Pre-existing wellbores"
plt += Wells.flag()

for a in plt.actors:
    # change scale to kilometers in x and y, but expand z scale by 1.5!
    a.scale([0.001, 0.001, 0.0015])

#########################
## 6. Done. show the plot
#########################
plt += __doc__
plt.show(viewup="z")

#exportWindow("page.html") # k3d is the default
```
geo

**Comment by ahinoamp** [comment]
Hi Marco,

Thanks so much for those tips!
I incorporated them into my jupyter notebook. 

It was a busy month last month, but I just got some free time and finally made the youtube tutorial to accompany the revised jupyter notebook in binder: https://youtu.be/raiIft8VeRU.

Thanks again for all your help,
Noe

**Comment by marcomusy** [comment]
Hi Ahinoam, you are a great teacher! and the video tutorial is so well done.. Thanks a lot for sharing it!!
M.

**Comment by marcomusy** [comment]
Dear Noe, as you see the name of the package has changed recently, it would be great if you could update the name and links in the youtube description! whenever you have time to do it!

_New feature_: you can now export a whole window by pressing `E`, put the file to your server or dropbox and share the link with other colleagues who can visualize and interact with it with command:
`vedo https://vtkplotter.embl.es/examples/geo_scene.npy`

**Comment by ahinoamp** [comment]
Hi @marcomusy ! 
Yes, I noticed the name change. Very cool typography. Though I wasn't sure whether the package should be called vedo or v3do?
I've updated the tutorial with the name and the links. Though I think the documentation link is the same.
Let me know if this is okay.
https://www.youtube.com/watch?v=raiIft8VeRU&feature=youtu.be

Thanks for the info on E the update.

I'm busy now coding and writing. I'll probably make public my repository in September, which uses vedo. Hopefully, I'll have time then to make some new tutorials. I'll let you know when I do.

**Comment by marcomusy** [comment]
Thanks! Yes the name is `vedo` and the link to the docs should be `vedo.embl.es` (although the old one still works)

Cool, let me know by then if you need any help with the package!

**Pull request merged**
