### PR TITLE
Added an exemple of the Tower of Hanoi

### PR DESCRIPTION
**Pull request by Gjacquenot**
It shows how to create an animated gif with vtkplotter

### CODE REVIEW

**Comment by marcomusy** [comment]
Thanks Guillaume!

**Comment by Gjacquenot** [comment]
Hi @marcomusy ,

Would you like me to use `os.system` to replace `subprocess` to avoid the warning check in my current pull request?

**Comment by marcomusy** [comment]
@Gjacquenot yes indeed that would be better..

**Comment by marcomusy** [comment]
@Gjacquenot I did the fix and moved the script to the simulations/ directory!
M.

**Comment by Gjacquenot** [comment]
Perfect! I am glad you integrate the Tower of Hanoi example coming from @gjbex

**Pull request merged**
